// <auto-generated />
using System;
using Assignment4.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment4.Migrations
{
    [DbContext(typeof(Assignment4DbContext))]
    partial class Assignment4DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment4.Models.Demographic", b =>
                {
                    b.Property<int>("DemographicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PopulationID")
                        .HasColumnType("int");

                    b.Property<int?>("CountyID")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("DemographicID");

                    b.HasIndex("PopulationID");

                    b.HasIndex("CountyID");

                    b.ToTable("Demographic");
                });

            modelBuilder.Entity("Assignment4.Models.Population", b =>
                {
                    b.Property<int>("PopulationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PopTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PopulationID");

                    b.ToTable("PopTypeName");
                });

            modelBuilder.Entity("Assignment4.Models.County", b =>
                {
                    b.Property<int>("CountyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountyID");

                    b.ToTable("County");
                });

            modelBuilder.Entity("Assignment4.Models.Demographic", b =>
                {
                    b.HasOne("Assignment4.Models.Population", "population")
                        .WithMany()
                        .HasForeignKey("PopulationID");

                    b.HasOne("Assignment4.Models.County", "county")
                        .WithMany()
                        .HasForeignKey("CountyID");
                });
#pragma warning restore 612, 618
        }
    }
}
